export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILURE = "ADD_REVIEW_FAILURE";
export const ADD_REVIEW_STARTED = "ADD_REVIEW_STARTED";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILURE = "GET_REVIEWS_FAILURE";
export const GET_REVIEWS_STARTED = "GET_REVIEWS_STARTED";
